### ISSUE TITLE
Could not load the shared library

### ISSUE THREAD

**Issue by puttimeth** [ARozar/multer-google-storage#41]
I use multer-google-storage in nestjs project and found this error when try to use it.

```
Error: Could not authenticate request
error:25078067:DSO support routines:win32_load:could not load the shared library
    at wrapError (C:\Users\PS3\Desktop\test-multer-google-storage\node_modules\multer-google-storage\node_modules\gcs-resumable-upload\src\index.ts:29:10)
    at C:\Users\PS3\Desktop\test-multer-google-storage\node_modules\multer-google-storage\node_modules\gcs-resumable-upload\src\index.ts:384:17
    at C:\Users\PS3\Desktop\test-multer-google-storage\node_modules\google-auto-auth\index.js:27:9
```

This error also occur when I reproduce them by
1. initialize project by nest cli `nest new project-name`
2. install package as follow `yarn add @types/multer multer-google-storage @google-cloud/storage @types/google-cloud__storage`
3. add the problem script to `app.controller.ts`

The result is as follow
`package.json`

```
"dependencies": {
    "@google-cloud/storage": "^5.16.0",
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/platform-express": "^8.0.0",
    "@types/google-cloud__storage": "^2.3.1",
    "@types/multer": "^1.4.7",
    "multer-google-storage": "^1.3.0",
    "reflect-metadata": "^0.1.13",
    "rimraf": "^3.0.2",
    "rxjs": "^7.2.0"
  },
```

the script in `app.controller.ts`
```
 // Store upload file
  @Post('upload')
  @UseInterceptors(FilesInterceptor('file', null, {
    storage: multerGoogleStorage.storageEngine({
      projectId: 'test_project',
      keyFilename: 'src/credential.json',
      bucket: 'test_bucket_00007',
      filename: (req, file, callback) => {
        const fileNameSplit = file.originalname.split('.');
        const fileExt = fileNameSplit[fileNameSplit.length - 1];
        callback(null, `${Date.now()}.${fileExt}`);
      }
    }),
    fileFilter: (req, file, callback) => {
      return file.mimetype.match(/image\/(jpg|jpeg|png)$/)
        ? callback(null, true)
        : callback(new BadRequestException('Only image file are allowed'), false);
    }
  }))
  uploadFile(@UploadedFile() file: Express.Multer.File) {
    console.log(file);    
  }
```

I look at the file that the error pointed to but there is no such file. Not sure it should be like this or not.
![image](https://user-images.githubusercontent.com/32786620/143825552-de9f7a4a-b2f4-48be-a253-64e9a73efa29.png)

**Comment by puttimeth** [comment]
(edit) For those who have the same problem, I fix it by replacing my current OpenSSL with version 1.1.1L and the problem goes away. Credit goes to this forum https://developer.salesforce.com/forums?id=9062I000000BmNHQA0
